#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightsensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port8,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          Flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members:
  Date:
  Period:
  Task Explanation & Description:
    This template is set where Flashlight is in motor1, rightMotor is in motor2, and servoMotor is in motor9
**Make sure that you are running:
                Robot / Platform Type / Vex Robotics / Vex 2.0 Cortex
                Robot / Platform Type / Natural Language PLTW
***When you attach the testbed, first plug in & turn on the power supply; then attach the USB to the computer, & only then turn the cortex on.


Pseudocode:
  Turn LED OR flashlight on for 3-8 secoseconds
  When limit or bump switch pressed, turn servo to ___ degrees / position
  when the 1st analog sensor is at ____, turn rightMotor on at ____ speed AND other light/LED on
  when 2nd analog sensor is at ____, turn both off
  end

*/

task main()
{																			//Program begins, insert code within curly braces
                                      //	set all things to 0 or off before start
turnFlashlightOn(Flashlight);
turnLEDOff(green);
setServo(servoMotor, -127);	  // many servo motors do not seem to be turning, but you can see their settings in the debugger window!
wait(5);

turnLEDOn(green);	 //	 choices of things to turn on
turnFlashlightOn(Flashlight, 127);	//
turnLEDOn(green);
startMotor(rightMotor,-64);			//
setServo(servoMotor, -127);			//	servomotors numbers correspond to POSITION or DEGREES, not speed!!
wait(5);	//

turnLEDOff(green);	//
turnFlashlightOff(Flashlight);	//
stopMotor(rightMotor);		//
setServo(servoMotor, 0);

untilTouch(limitSwitch);	 // could also do untilTouch(bumpSwitch)
turnFlashlightOn(Flashlight, 127);	//
setServo(servoMotor, 127);		 //
wait(10);	 //

while(SensorValue[sonar] > 12)	// looking at sonar, & waiting (as long as it reads over 12 inches)
	// could use ANY sensor, checking for ANY value (quad encoder, potentiomter, light sensor, line follower / dark sensor)
{
	wait(.1);
}
// once no longer waiting, do these things ...
turnLEDOn(green);	 //	 choices of things to turn on
turnFlashlightOn(Flashlight, 127);	//
turnLEDOn(green);
startMotor(rightMotor,-64);			//
wait(5);	//

if(SensorValue[sonar] > 12)		// looking at sonar, & if over 12 inches, waiting; could use ANY sensor, checking for ANY value
{
	wait(.1);
}
else // if the value is not ove 12 inches, do this stuff instead
{
	turnLEDOn(green);	 //	 choices of things to turn on
	turnFlashlightOn(Flashlight, 127);	//
	turnLEDOn(green);
	startMotor(rightMotor,-64);			//
	wait(5);	//
}

turnLEDOff(green);	//  make sure everyting is off at the end
turnFlashlightOff(Flashlight);	//
stopMotor(rightMotor);		//
setServo(servoMotor, 0);


}   // last line of main program
