#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightsensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:Activity 3.2.3
  Team Members:Daniel Zhong
  Date:4/17/17
  Period:4

  Task Description:Writing the code for the machine.


  Pseudocode:
  Turn LED OR flashlight on for 3-8 secoseconds
  When limit or bump switch pressed, turn servo to ___ degrees / position
  when the 1st analog sensor is at ____, turn rightMotor on at ____ speed AND other light/LED on
  when 2nd analog sensor is at ____, turn both off
  end


*/

{                                     //Program begins, insert code within curly braces

turnFlashlightOn(Flashlight, 127);  //Turn Flashlight brightest
wait(5);  //wait 5 seconds
turnFlashlightOff(Flashlight);  //Turn Flashlight off
while(SensorValue[limitSwitch] == 1) //Whlie limit switch pressed
{
setServo(servoMotor,  -127);  // servomotor turn counterclockwise for full speed
}
while(SensorValue[potentiometer] <= 1800)//when potentiometer has less than 1800
{
startMotor(rightMotor, 127);   	// right motor turn clockwise for full speed
turnLEDOn(green);  // turn green led on
}
while(SensorValue[sonar] > 600)//while sonar values greater than 600
{
stopMotor(rightMotor);  	//Stop right motor
turnLEDOff(green);  ////turn led off
stopMotor(servoMotor);//Stop servo Motor
}
}
